export const DOMAINS = [
  'Web Development',
  'Data Science',
  'UI/UX Design',
  'Mobile Development',
  'AI/ML',
  'DevOps & Cloud',
  'Blockchain',
  'Cybersecurity',
  'Software Engineering',
  'Management',
  'Marketing',
  'Finance',
  'Human Resources (HR)',
  'Operations',
  'Sales',
  'Content Writing',
  'Graphic Design',
  'Data Entry',
  'Consulting',
  'Mechanical Engineering',
  'Civil Engineering',
  'Electrical Engineering',
  'Electronics & Communication',
  'BCA/MCA',
  'Research',
  'Architecture',
  'Product Management',
  'Business Analytics'
];
